import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    { type: 'doc', id: 'about', label: 'About' },
    { type: 'doc', id: 'getting-started', label: 'Getting Started' },
    { type: 'doc', id: 'cli', label: 'CLI Reference' },
    { type: 'doc', id: 'api', label: 'API Reference' },
    { type: 'doc', id: 'auto-translation', label: 'Auto-Translation' },
    {
      type: 'category',
      label: 'Features',
      items: [{ type: 'autogenerated', dirName: 'features' }],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [{ type: 'autogenerated', dirName: 'guides' }],
    },
  ],
};

export default sidebars;
