/**
 * Generates the file header for generated TypeScript type files.
 * Includes warnings, bundle identifier, and disable comments.
 */
export function generateFileHeader(bundleKey: string): string {
  return `/* eslint-disable */
// prettier-ignore
/**
 * Auto-generated translation keys for bundle: ${bundleKey}
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Changes will be overwritten on next generation
 *
 * To regenerate: lingo-tracker bundle
 */`;
}
