import { generateFileHeader } from './file-header';

describe('File Header Generator', () => {
  it('should generate header with bundle name', () => {
    const bundleKey = 'common';
    const header = generateFileHeader(bundleKey);

    expect(header).toContain(
      'Auto-generated translation keys for bundle: common',
    );
    expect(header).toContain('DO NOT EDIT THIS FILE MANUALLY');
    expect(header).toContain('To regenerate: lingo-tracker bundle');
  });

  it('should include disable comments', () => {
    const header = generateFileHeader('test');

    expect(header).toContain('/* eslint-disable */');
    expect(header).toContain('// prettier-ignore');
  });

  it('should not include timestamp', () => {
    const header = generateFileHeader('test');

    // Check for common timestamp formats
    expect(header).not.toMatch(/\d{4}-\d{2}-\d{2}/); // YYYY-MM-DD
    expect(header).not.toMatch(/\d{2}:\d{2}:\d{2}/); // HH:MM:SS
  });
});
