import { TranslocoTestingModule, type TranslocoTestingOptions } from '@jsverse/transloco';

/**
 * Creates a configured TranslocoTestingModule for unit tests.
 *
 * This helper provides a consistent Transloco setup across all test specs,
 * including all required providers (TRANSLOCO_TRANSPILER, etc.) and preloaded translations.
 *
 * @param options - Optional Transloco testing configuration overrides
 * @returns Configured TranslocoTestingModule
 */
export function getTranslocoTestingModule(options: TranslocoTestingOptions = {}) {
  return TranslocoTestingModule.forRoot({
    langs: {
      en: {
        'browser.backButton': 'Back to collections',
        'browser.filterFolders': 'Filter folders...',
        'browser.loadingFolders': 'Loading folders...',
        'browser.noFoldersMatchSearch': 'No folders match your search',
        'browser.noFoldersFound': 'No folders found',
        'browser.clickToLoad': 'click to load',
        'browser.loadingCollectionConfiguration': 'Loading collection configuration...',
        'browser.loadingTranslations': 'Loading translations...',
        'browser.noTranslationsFoundInFolder': 'No translations found in this folder.',
        'browser.searchTranslations': 'Search (min 3 characters)...',
        'browser.showingSearchResultsForX': 'Showing search results for "{{ query }}"',
        'browser.clearSearch': 'Clear Search',
        'browser.noFolderSelected': 'No resource folder selected',
        'browser.addTranslationButton': 'Add Translation',
        'browser.sortAscending': 'Sort ascending',
        'browser.sortDescending': 'Sort descending',
        'browser.sortAscendingTooltip': 'Sort ascending (A→Z)',
        'browser.sortDescendingTooltip': 'Sort descending (Z→A)',
        'browser.selectFolderFirst': 'Select a folder first',
        'browser.addNewTranslationTooltip': 'Add a new translation',
        'browser.noTranslation': 'No translation',
        'browser.commentPrefix': 'Comment:',
        'browser.toggleExpansion': 'Toggle expansion',
        'browser.noResults': 'No results found',
        'browser.density.compactTooltip': 'Compact — 2-line view, high density',
        'browser.density.fullTooltip': 'Full — detailed view with comments and all locales',
        'browser.dialog.deleteFolder.title': 'Delete Folder',
        'browser.dialog.deleteFolder.messageX': 'Delete "{{name}}" and all its contents?',
        'browser.dialog.deleteResource.title': 'Delete Resource',
        'browser.dialog.deleteResource.messageX':
          'Are you sure you want to delete the resource "{{key}}"? This action cannot be undone.',
        'browser.dialog.moveFolder.title': 'Move Folder',
        'browser.dialog.moveFolder.messageX': 'Move folder "{{name}}" and all its contents to "{{dest}}"?',
        'browser.folderInput.placeholder': 'Folder name',
        'browser.folderInput.nameRequired': 'Folder name is required',
        'browser.folderInput.namePatternError': 'Only letters, numbers, dashes, and underscores allowed',
        'browser.folderNode.newChip': 'New',
        'browser.folderPicker.folderAriaLabelX': 'Folder {{ name }}',
        'browser.folderPicker.collapse': 'Collapse',
        'browser.folderPicker.expand': 'Expand',
        'browser.folderPicker.addSubfolderToX': 'Add subfolder to {{ name }}',
        'browser.folderPicker.folderLabel': 'Folder:',
        'browser.folderPicker.noFoldersYet': 'No folders yet',
        'browser.folderPicker.createFirstFolder': 'Create First Folder',
        'browser.folderPicker.folderCreated': 'Folder created successfully',
        'browser.folderPicker.folderAlreadyExists': 'Folder already exists',
        'browser.folderPicker.createFolderFailed': 'Failed to create folder',
        'browser.folderPicker.rootLabel': 'root',
        'browser.indexingOverlay.message': 'Indexing collection...',
        'browser.indexingOverlay.errorTitle': 'Indexing Failed',
        'browser.indexingOverlay.defaultError': 'An error occurred while indexing the collection.',
        'browser.placeholder.title': 'Translation Browser Coming Soon',
        'browser.placeholder.message':
          "The translation browser feature is currently under development. Soon you'll be able to view, edit, and manage all translations within this collection.",
        'browser.placeholder.collection': 'Collection',
        'browser.similarTranslations.title': 'Similar Translations',
        'browser.similarTranslations.idle': 'Similar translations will appear as you type',
        'browser.similarTranslations.loading': 'Searching for similar translations...',
        'browser.similarTranslations.empty': 'No similar translations found',
        'browser.similarTranslations.showMoreX': 'Show {{ count }} more',
        'browser.status.new': 'New',
        'browser.status.stale': 'Stale',
        'browser.status.translated': 'Translated',
        'browser.status.verified': 'Verified',
        'browser.statusFilter.needsWork': 'Needs Work',
        'browser.toast.copiedToClipboard': 'Copied to clipboard',
        'browser.toast.copyFailed': 'Failed to copy',
        'browser.toast.resourceDeleted': 'Resource deleted successfully',
        'browser.toast.deleteFailed': 'Failed to delete resource',
        'browser.toast.translateFailed': 'Failed to auto-translate resource',
        'browser.toast.translationUpdated': 'Translation updated successfully',
        'browser.toast.localeTranslated': '1 locale translated successfully',
        'browser.toast.localesTranslatedX': '{{count}} locales translated successfully',
        'browser.toast.allLocalesUpToDate': 'All locales are already up to date',
        'browser.toast.skippedLocalesX': 'Skipped locales (ICU format): {{locales}}',
        'browser.toast.resourceCreated': 'Resource created successfully',
        'browser.toast.autoTranslationSkippedX': 'Auto-translation skipped for {{locales}} (ICU format not supported)',
        'browser.toast.resourceAlreadyInFolder': 'Resource is already in this folder',
        'browser.toast.resourceMovedX': 'Moved "{{name}}" to {{folder}}',
        'browser.toast.folderAlreadyAtLocation': 'Folder is already at this location',
        'browser.toast.folderMovedX': 'Moved "{{name}}" into {{dest}}',
        'browser.toast.moveResourceFailed': 'Failed to move resource',
        'browser.toast.moveFolderFailed': 'Failed to move folder',
        'browser.translationEditor.closeDialog': 'Close dialog',
        'browser.translationEditor.translationKey': 'Translation Key',
        'browser.translationEditor.keyHint': 'Use only letters, numbers, underscores, and hyphens',
        'browser.translationEditor.baseBadge': 'Base',
        'browser.translationEditor.localeTranslationX': '{{ locale }} Translation',
        'browser.translationEditor.enterTranslationX': 'Enter {{ locale }} translation...',
        'browser.translationEditor.baseValueRequired': 'Base translation is required',
        'browser.translationEditor.commentLabel': 'Comment (Optional)',
        'browser.translationEditor.commentPlaceholder': 'Add context for translators...',
        'browser.translationEditor.commentHint': 'Provide context or instructions for translators',
        'browser.translationEditor.otherLocalesToggleX': 'Add translations for other locales ({{ count }} available)',
        'browser.translationEditor.status': 'Status',
        'browser.translationEditor.saving': 'Saving...',
        'browser.translationEditor.editTitle': 'Edit Translation',
        'browser.translationEditor.createTitle': 'Create Translation',
        'browser.translationEditor.editSubtitle': 'Update translation values and metadata',
        'browser.translationEditor.createSubtitle': 'Add a new translation entry to your collection',
        'browser.translationEditor.updateButton': 'Update Translation',
        'browser.translationEditor.saveButton': 'Save Translation',
        'browser.translationEditor.keyCopied': 'Similar resource key copied',
        'browser.translationEditor.copyFailed': 'Failed to copy',
        'browser.translationEditor.keyRequired': 'Translation key is required',
        'browser.translationEditor.keyPatternError': 'Only letters, numbers, underscores, and hyphens allowed',
        'browser.translationEditor.commentConfirm.title': 'No Comment Added',
        'browser.translationEditor.commentConfirm.message':
          'Comments help other translators understand context. Are you sure you want to save without a comment?',
        'browser.translationEditor.commentConfirm.saveAnyway': 'Save Anyway',
        'browser.translationEditor.commentConfirm.addComment': 'Add Comment',
        'browser.translationEditor.conflict.title': 'Translation Key Already Exists',
        'browser.translationEditor.conflict.messageX':
          'The translation key "{{ key }}" already exists in this collection. Would you like to edit the existing translation or choose a different key?',
        'browser.translationEditor.conflict.editExisting': 'Edit Existing',
        'browser.translationEditor.conflict.chooseDifferentKey': 'Choose Different Key',
        'browser.translationEditor.error.missingResource': 'Cannot update: resource data is missing',
        'browser.translationEditor.error.keyRenamingNotSupported':
          'Key renaming is not yet supported. Please use the same key or create a new resource.',
        'browser.translationEditor.error.notFound': 'Resource not found. It may have been deleted.',
        'browser.translationEditor.error.invalidRequest': 'Invalid request',
        'browser.translationEditor.error.createFailed': 'Failed to create translation',
        'browser.translationEditor.error.updateFailed': 'Failed to update translation',
        'browser.translationEditor.error.unexpected': 'An unexpected error occurred',
        'common.actions.edit': 'Edit',
        'common.actions.delete': 'Delete',
        'common.actions.retry': 'Retry',
        'common.actions.cancel': 'Cancel',
        'common.actions.ok': 'OK',
        'common.actions.save': 'Save',
        'common.actions.back': 'Back',
        'common.actions.clickToCopy': 'click to copy',
        'common.actions.move': 'Move',
        'common.actions.translate': 'Translate',
        'common.actions.selectAll': 'Select All',
        'common.actions.clearAll': 'Clear All',
        'common.actions.close': 'Close',
        'common.actions.dismiss': 'Dismiss',
      },
    },
    translocoConfig: {
      availableLangs: ['en'],
      defaultLang: 'en',
    },
    preloadLangs: true,
    ...options,
  });
}
